name: app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: "^0.9.2"
  google_fonts: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/coffee_1.jpg
    - assets/image/coffee_2.jpeg
    - assets/image/coffee_3.jpeg
    - assets/image/profil.png
    - assets/image/profil.webp
    - assets/video/font.mp4